# Generated by Django 4.2.5 on 2023-10-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hunter_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='imagen',
        ),
        migrations.AddField(
            model_name='personal',
            name='foto',
            field=models.ImageField(default='img/default.png', upload_to='img/'),
        ),
    ]
