# Generated by Django 4.2.5 on 2023-10-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hunter_App', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
